import dayjs from 'dayjs';

export const USER_MIN_LENGH_NAME = 3;
export const USER_MAX_LENGH_NAME = 40;
export const USER_MIN_AGE = 18;
export const USER_MAX_AGE = 90;
export const USER_MIN_LENGH_PASSWORD = 3;
export const USER_MAX_LENGH_PASSWORD = 40;

export const COMPETITIONGLOBAL_MIN_LENGH_NAME = 3;
export const COMPETITIONGLOBAL_MAX_LENGH_NAME = 40;
export const COMPETITIONGLOBAL_MIN_LENGH_SEASON = 3;
export const COMPETITIONGLOBAL_MAX_LENGH_SEASON = 10;

export const RULE_COMPETITIONTYPE_LEAGUE = 1;
export const RULE_COMPETITIONTYPE_CUP = 2;

export const MANAGERGLOBAL_MIN_LENGH_NAME = 3;
export const MANAGERGLOBAL_MAX_LENGH_NAME = 40;
export const MANAGERGLOBAL_MIN_AGE = 18;
export const MANAGERGLOBAL_MAX_AGE = 90;

export const PLAYERGLOBAL_PRIMARY_POSITION_RATING = 1.0;
export const PLAYERGLOBAL_SECONDARY_POSITION_RATING = 0.95;
export const PLAYERGLOBAL_SAME_AREA_PRIMARY_POSITION_RATING = 0.8;
export const PLAYERGLOBAL_SAME_AREA_SECONDARY_POSITION_RATING = 0.7;
export const PLAYERGLOBAL_NON_PLAYING_POSITION_RATING = 0.3;
export const PLAYERGLOBAL_DEFAULT_GOALKEEPER_POSITION_RATING = 5;
export const PLAYERGLOBAL_MIN_LENGH_NAME = 3;
export const PLAYERGLOBAL_MAX_LENGH_NAME = 40;
export const PLAYERGLOBAL_MIN_AGE = 14;
export const PLAYERGLOBAL_MAX_AGE = 50;
export const PLAYERGLOBAL_MIN_OVERALL = 1;
export const PLAYERGLOBAL_MAX_OVERALL = 100;
export const PLAYERGLOBAL_MIN_PRIMARY_POSITIONS = 1;
export const PLAYERGLOBAL_MAX_PRIMARY_POSITIONS = 3;
export const PLAYERGLOBAL_MAX_SECONDARY_POSITIONS = 5;

export const TEAMGLOBAL_MIN_LENGH_NAME = 3;
export const TEAMGLOBAL_MAX_LENGH_NAME = 40;
export const TEAMGLOBAL_MIN_PLAYERSGLOBAL = 1;
export const TEAMGLOBAL_MAX_PLAYERSGLOBAL = 40;

export const SAVE_MIN_LENGH_NAME = 3;
export const SAVE_MAX_LENGH_NAME = 40;
export const SAVE_MIN_LENGH_MANAGER_NAME = MANAGERGLOBAL_MIN_LENGH_NAME;
export const SAVE_MAX_LENGH_MANAGER_NAME = MANAGERGLOBAL_MAX_LENGH_NAME;
export const SAVE_MIN_MANAGER_AGE = MANAGERGLOBAL_MIN_AGE;
export const SAVE_MAX_MANAGER_AGE = MANAGERGLOBAL_MAX_AGE;

export const CURRENT_DATE_UTC = dayjs();
export const DATE_FORMAT = 'DD/MM/YYYY';
export const DATETIME_FORMAT = 'DD/MM/YYYY [às] HH:mm';
export const DEFAULT_DATE_FORMAT = 'YYYY-MM-DD';
export const DEFAULT_DATETIME_FORMAT = 'YYYY-MM-DD [at] HH:mm';
